# Generated by Django 3.2.16 on 2022-12-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_medical_records_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical_records',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
