# Generated by Django 3.2.16 on 2022-12-22 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_profile_phone_number'),
        ('health', '0003_medical_records_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=500)),
                ('state', models.TextField(max_length=500)),
                ('date', models.DateTimeField()),
                ('procedure', models.TextField()),
                ('other', models.TextField()),
                ('health_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profile')),
            ],
        ),
    ]
