# Generated by Django 3.2.16 on 2022-12-22 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_profile_user'),
        ('health', '0004_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Declined', 'Declined'), ('Accepted', 'Accepted')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='the_patient', to='authentication.profile'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='health_worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='authentication.profile'),
        ),
    ]
