# Generated by Django 3.2.16 on 2022-12-22 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_profile_user'),
        ('health', '0005_auto_20221222_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Health_worker_stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=100)),
                ('accepted', models.IntegerField()),
                ('declined', models.IntegerField()),
                ('health_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_worker_stat', to='authentication.profile')),
            ],
        ),
    ]
