# Generated by Django 3.2.16 on 2022-12-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_health_worker_stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='health_worker_stat',
            name='year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='health_worker_stat',
            name='month',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
