# Generated by Django 3.2.16 on 2022-12-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0007_auto_20221222_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health_worker_stat',
            name='accepted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='health_worker_stat',
            name='declined',
            field=models.IntegerField(default=0),
        ),
    ]
